# https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:

  ### Go Workspace ##################################
  go-workspace:
      build:
        context: ./go-workspace
        args:
          - BASE_IMAGE_TAG_PREFIX=${UBUNTU_BASE_IMAGE_TAG_PREFIX}
          - GO_VERSION=${GO_VERSION}
          - GO111MODULE=${GO111MODULE}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      ports:
        - "${GO_WORKSPACE_API_SERVE_HOST_PORT}:8080"
      tty: true
      environment:
        - WORKSPACENAME=${WORKSPACENAME}
      depends_on:
        - mysql
        - redis
        - etcd
      networks:
        - frontend
        - backend

  ### MySQL ################################################
  mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

  ### Redis ################################################
  redis:
      build: ./redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - backend

  ### Etcd ################################################
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2399:2379
      - 2388:2380
    networks:
      - backend

  ### e3w ################################################     
  e3w:
    image: soyking/e3w:latest
    ports:
      - "8088:8080"
    volumes:
      - ./e3w/config.ini:/app/conf/config.default.ini
    networks:
      - backend
    depends_on: 
      - etcd
  ### Cassandra ############################################
  cassandra:
    build: ./cassandra
    ports:
      - "${CASSANDRA_TRANSPORT_PORT_NUMBER}:7000"
      - "${CASSANDRA_JMX_PORT_NUMBER}:7199"
      - "${CASSANDRA_CQL_PORT_NUMBER}:9042"
    privileged: true
    environment:
      - CASSANDRA_VERSION=${CASSANDRA_VERSION}
      - CASSANDRA_TRANSPORT_PORT_NUMBER=${CASSANDRA_TRANSPORT_PORT_NUMBER}
      - CASSANDRA_JMX_PORT_NUMBER=${CASSANDRA_JMX_PORT_NUMBER}
      - CASSANDRA_CQL_PORT_NUMBER=${CASSANDRA_CQL_PORT_NUMBER}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD_SEEDER=${CASSANDRA_PASSWORD_SEEDER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - CASSANDRA_NUM_TOKENS=${CASSANDRA_NUM_TOKENS}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
      - CASSANDRA_ENABLE_RPC=${CASSANDRA_ENABLE_RPC}
      - CASSANDRA_DATACENTER=${CASSANDRA_DATACENTER}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
    hostname: laradock-cassandra
    volumes:
      - ${DATA_PATH_HOST}/cassandra:/var/lib/cassandra
    networks:
      - backend

  ### MongoDB ##############################################
  mongo:
    build: ./mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
      - ${DATA_PATH_HOST}/mongo_config:/data/configdb
    networks:
      - backend

  ### MongoWebUI ################################################
  mongo-webui:
    build:
      context: ./mongo-webui
    environment:
      - ROOT_URL=${MONGO_WEBUI_ROOT_URL}
      - MONGO_URL=${MONGO_WEBUI_MONGO_URL}
      - INSTALL_MONGO=${MONGO_WEBUI_INSTALL_MONGO}
    volumes:
      - ${DATA_PATH_HOST}/mongo-webui:/data/db
    ports:
      - "${MONGO_WEBUI_PORT}:3000"
    networks:
      - backend
    depends_on:
      - mongo